### PR TITLE
added created_at

### PR DESCRIPTION
**Pull request by YoshinariYamanaka**
This is for https://github.com/tabi-memo/frontend/pull/11#discussion_r1414690951

Added created_at and applied `pnpm supabase db reset`

### CODE REVIEW

**Comment by YoshinariYamanaka** [comment]
@Kana-TAGUCHI @samuraikun 
Could you please check !

**Review by samuraikun — APPROVED** [review]
I've forgotten `created_at` column 🙇 
Thank you!

**Review by kanatagu — APPROVED** [review]
Thank you!!

**Comment by YoshinariYamanaka** [comment]
Thank guys !

**Pull request merged**
